-- Sacrifice Blunt franchise database — initial schema
-- Mirrors src/data/dataset.json one-to-one. Load data with supabase/seed.sql
-- (generated by `npm run build:sql`).
--
-- Principles
--   * one franchise, many eras (COTC → Sacrifice Blunt); team_name_at_time lives on seasons/games
--   * unknown values are NULL, never 0
--   * every historical row carries a confidence level and a source reference
--   * batting stats are derived from plate_appearances (or player_game_stats aggregates)

create type confidence_level as enum (
  'verified', 'confirmed', 'partial', 'unknown',
  'verified_regular_season_only', 'mixed_verified_and_confirmed'
);
create type game_stage as enum ('regular', 'postseason');
create type game_status as enum ('final', 'final_result_only', 'unreported', 'scheduled', 'postponed', 'in_progress');
create type game_result as enum ('W', 'L', 'T');
create type pa_result as enum ('1B', '2B', '3B', 'HR', 'BB', 'HBP', 'K', 'OUT', 'SAC', 'ROE', 'FC');

create table franchise (
  id text primary key,
  current_name text not null,
  original_name text not null,
  earliest_verified_season_id text,
  home_complex text,
  notes text
);

create table eras (
  id text primary key,
  franchise_id text not null references franchise(id),
  name text not null,
  display_name text not null,
  first_season_id text,
  last_season_id text,
  start_note text,
  end_note text,
  logo_treatment text,
  notes text
);

create table source_evidence (
  id text primary key,
  kind text not null,              -- teamsideline_export | physical_plaque | leadership_confirmation | photo | other
  title text not null,
  file_path text,                  -- repo path or storage key
  public_url text,
  coverage text,
  confidence confidence_level not null default 'verified',
  created_at timestamptz not null default now()
);

create table seasons (
  id text primary key,             -- e.g. 2026-spring
  slug text unique not null,
  franchise_id text not null references franchise(id) default 'sacrifice-blunt',
  era_id text not null references eras(id),
  year int not null,
  session text not null,           -- Spring | Summer | Summer/Fall | Fall
  sort_key int not null,
  team_name_at_time text not null,
  league text,
  division text,
  league_size int,
  regular_wins int, regular_losses int, regular_ties int,
  regular_place int,
  postseason_wins int, postseason_losses int,
  overall_wins int, overall_losses int, overall_ties int,
  overall_source text,
  playoff_finish text,
  playoff_finish_code text,
  champion boolean not null default false,
  title_under_review boolean not null default false,
  undefeated boolean not null default false,
  confidence confidence_level not null,
  regular_confidence confidence_level not null,
  postseason_confidence confidence_level not null default 'unknown',
  championship_note text,
  postseason_note text,
  regular_season_note text,
  source_notes text,
  schedule_revision text,
  playoff_revision text
);

create table season_sources (
  season_id text references seasons(id) on delete cascade,
  source_evidence_id text references source_evidence(id),
  primary key (season_id, source_evidence_id)
);

create table opponents (
  id text primary key,
  slug text unique not null,
  canonical_name text not null,
  aliases text[] not null default '{}'
);

-- full printed standings per season (league context)
create table standings (
  season_id text references seasons(id) on delete cascade,
  place int not null,
  team text not null,
  is_franchise boolean not null default false,
  opponent_id text references opponents(id),
  w int, l int, t int, gb text, gp int, pct numeric(4,3), streak text, coach text,
  primary key (season_id, team)
);

create table games (
  id text primary key,             -- e.g. 2026-fall-cheers-1
  slug text unique not null,
  season_id text not null references seasons(id) on delete cascade,
  date date,
  time text,
  field text,
  opponent_id text not null references opponents(id),
  home_away text check (home_away in ('home', 'away')),
  team_score int,
  opponent_score int,
  result game_result,
  status game_status not null,
  stage game_stage not null,
  week int,
  playoff_round int,
  playoff_round_label text,
  bracket_game text,
  is_title_game boolean not null default false,
  team_name_at_time text,
  confidence confidence_level not null,
  source_evidence_id text references source_evidence(id),
  notes text[] not null default '{}',
  finalized_at timestamptz,
  check ((team_score is null) = (opponent_score is null))
);
create index on games (season_id, date);
create index on games (opponent_id);

-- every game on the league slate (not just ours) for brackets / standings context
create table league_games (
  id bigserial primary key,
  season_id text not null references seasons(id) on delete cascade,
  date date, time text, field text,
  stage game_stage not null, week int, round int, round_label text, bracket_game text,
  away text not null, home text not null,
  away_score int, home_score int, away_result text, home_result text,
  status game_status not null,
  notes text[] not null default '{}'
);

create table players (
  id text primary key,             -- slug
  slug text unique not null,
  name text not null,
  short_name text,
  number text,
  positions text[] not null default '{}',
  active boolean not null default true,
  photo text,
  bio text,
  confidence confidence_level not null default 'confirmed',
  source text
);

create table season_rosters (
  season_id text references seasons(id) on delete cascade,
  player_id text references players(id) on delete cascade,
  number text,
  positions text[] not null default '{}',
  confidence confidence_level not null default 'confirmed',
  primary key (season_id, player_id)
);

create table game_lineups (
  game_id text references games(id) on delete cascade,
  player_id text references players(id),
  batting_order int not null,
  position text,
  primary key (game_id, batting_order)
);

create table plate_appearances (
  id bigserial primary key,
  game_id text not null references games(id) on delete cascade,
  player_id text not null references players(id),
  pa_index int not null,           -- order within the game
  inning int,
  result pa_result not null,
  rbi int not null default 0,
  run_scored boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  unique (game_id, pa_index)
);

-- imported aggregate lines when PA detail does not exist; NULL = not captured
create table player_game_stats (
  game_id text references games(id) on delete cascade,
  player_id text references players(id),
  pa int, ab int, r int, h int, singles int, doubles int, triples int, hr int,
  rbi int, bb int, k int, sac int, roe int,
  source_evidence_id text references source_evidence(id),
  primary key (game_id, player_id)
);

create table championships (
  id text primary key,
  slug text unique not null,
  season_id text unique not null references seasons(id),
  title text not null,
  team_name_at_time text not null,
  confidence confidence_level not null,
  verification text[] not null default '{}',   -- teamsideline_playoff_results | championship_plaque | team_leadership
  undefeated boolean not null default false,
  title_game_id text references games(id),
  evidence_image text,
  notes text
);

create table awards (
  id bigserial primary key,
  season_id text references seasons(id),
  player_id text references players(id),
  name text not null,
  confidence confidence_level not null,
  source_evidence_id text references source_evidence(id),
  notes text
);

create table milestones (
  id bigserial primary key,
  game_id text references games(id),
  player_id text references players(id),
  kind text not null,              -- e.g. career_hits_100, franchise_win_100
  value int,
  achieved_on date,
  confidence confidence_level not null,
  notes text
);

-- records are computed from games/PAs; this table stores reviewed/pinned record entries
create table records (
  id bigserial primary key,
  scope text not null check (scope in ('team', 'individual')),
  category text not null,
  holder_player_id text references players(id),
  season_id text references seasons(id),
  game_id text references games(id),
  value numeric,
  display_value text,
  confidence confidence_level not null,
  notes text
);

create table media (
  id bigserial primary key,
  kind text not null,              -- photo | video | document
  url text not null,
  caption text,
  season_id text references seasons(id),
  game_id text references games(id),
  player_id text references players(id),
  credit text
);

create table review_queue (
  id text primary key,
  entity text not null,
  entity_id text,
  severity text not null check (severity in ('info', 'decision', 'error')),
  message text not null,
  resolved_at timestamptz
);

-- Derived batting view (season + career built on top of this)
create view batting_game_lines as
select
  pa.game_id, pa.player_id,
  count(*)                                                      as pa,
  count(*) filter (where result not in ('BB','HBP','SAC'))      as ab,
  count(*) filter (where run_scored)                            as r,
  count(*) filter (where result in ('1B','2B','3B','HR'))       as h,
  count(*) filter (where result = '1B')                         as singles,
  count(*) filter (where result = '2B')                         as doubles,
  count(*) filter (where result = '3B')                         as triples,
  count(*) filter (where result = 'HR')                         as hr,
  sum(rbi)                                                      as rbi,
  count(*) filter (where result = 'BB')                         as bb,
  count(*) filter (where result = 'HBP')                        as hbp,
  count(*) filter (where result = 'K')                          as k,
  count(*) filter (where result = 'SAC')                        as sac,
  count(*) filter (where result = 'ROE')                        as roe
from plate_appearances pa
group by pa.game_id, pa.player_id;

-- Public read, admin write. Admins are users with app_metadata.role = 'admin'.
do $$
declare t text;
begin
  foreach t in array array['franchise','eras','source_evidence','seasons','season_sources','opponents','standings','games',
    'league_games','players','season_rosters','game_lineups','plate_appearances','player_game_stats','championships',
    'awards','milestones','records','media']
  loop
    execute format('alter table %I enable row level security', t);
    execute format('create policy "public read" on %I for select using (true)', t);
    execute format($p$create policy "admin write" on %I for all
      using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
      with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')$p$, t);
  end loop;
end $$;

-- review queue is admin-only (no public read)
alter table review_queue enable row level security;
create policy "admin all" on review_queue for all
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
